import type { Role } from "./types";

const COMMON_REVIEW = "Every change is reviewed by a person before it merges. Nothing merges itself.";
const COMMON_DECISIONS = "Contribution earns factual thanks. It never earns governance weight, ranking influence or data access.";

export const ROLES: Role[] = [
  {
    slug: "engineers",
    name: "Engineers and maintainers",
    summary: "Build and review one small, owned piece of the server, the app or this site.",
    stage: "founding",
    urgency: "most-urgent-now",
    pictogram: "electrician",
    doNow: [
      "Make the code that already exists safer and sturdier first: tests, edge cases, clearer errors, smaller functions. This comes before new features.",
      "Take one plan unit sized for about an hour: one endpoint, one screen, one test or one check.",
      "Review a pull request in an area you know well.",
      "Improve setup: shorter steps, fewer surprises, clearer errors.",
    ],
    prerequisites: [
      "Node 24 or newer, Docker and Python 3 for the full setup. The site alone needs only Node.",
      "No special tools, and the skills folders under .claude are not required.",
      "You can work by hand or with an assistant of your choice.",
    ],
    time: ["About one hour for one unit.", "A few hours across a week for a larger piece.", "A single review, whenever you have time."],
    privacyAndConflict: [
      "Use made up data only. Never paste real emails, names or evidence into code, tests or fixtures.",
      "Say so in the pull request if you work for a company that could gain from a choice you touch.",
    ],
    prohibited: [
      "Changing the status of a plan unit yourself. Maintainers confirm status.",
      "Reopening a settled decision in a pull request. Use an open question instead.",
      "Merging your own change, or sending bulk or unsolicited automated pull requests.",
    ],
    tasks: { areas: ["can-server", "can-app", "can-gallery", "can-root"] },
    review: [COMMON_REVIEW, "A maintainer owns each area and confirms status. High risk areas such as sign in, privacy and moderation need designated reviewers.", "If something looks unsafe, stop and use the private route in SECURITY.md."],
    decisions: [COMMON_DECISIONS, "Settled choices are in the decisions log. To challenge one, add evidence to the matching open question."],
    links: [
      { label: "How to contribute", doc: "CONTRIBUTING.md" },
      { label: "The contribution ladder", doc: "docs/spec/21-open-source-governance.md" },
      { label: "AI contribution policy", doc: "docs/spec/22-ai-contribution-policy.md" },
      { label: "Good first units", doc: "docs/contributing/good-first-units.md" },
      { label: "All one hour tasks", internal: "/contribute/tasks/" },
    ],
  },
  {
    slug: "designers",
    name: "Designers",
    summary: "Improve one flow, one screen or one set of design tokens, and say why in plain words.",
    stage: "founding",
    urgency: "most-urgent-now",
    pictogram: "clerk",
    doNow: [
      "Review one wireframe or flow against the written design and say where a person could get lost.",
      "Improve wording in the copy deck so it is shorter and kinder.",
      "Propose a change to the design tokens, with the contrast numbers.",
      "Check a screen at small sizes and with large text.",
    ],
    prerequisites: ["A browser and a text editor are enough. A design tool is welcome but not required.", "Read the design folder first. It holds the flows, components and tokens."],
    time: ["About one hour for one flow review.", "A few hours for a small set of screens."],
    privacyAndConflict: [
      "Draw with fictional people and places only, and label them as fictional examples.",
      "Do not use screenshots of real services that show real people's details.",
    ],
    prohibited: [
      "Work that copies another product's brand, or uses a real organisation's name or look.",
      "Dark patterns: countdowns, guilt, or anything that pushes people to post more.",
      "Any design that ranks people or problems by popularity.",
    ],
    tasks: { note: "No bounded design task is open in the task list right now." },
    review: [COMMON_REVIEW, "A maintainer for the app or this site checks the change against the design documents and the accessibility baseline."],
    decisions: [COMMON_DECISIONS, "Design choices that need a decision become an open question. Your evidence goes there."],
    links: [
      { label: "Design documents", doc: "docs/design/README.md" },
      { label: "User experience specification", doc: "docs/spec/17-ux.md" },
      { label: "Open questions", internal: "/open-questions/" },
      { label: "All one hour tasks", internal: "/contribute/tasks/" },
    ],
  },
  {
    slug: "accessibility",
    name: "Accessibility reviewers",
    summary: "Try one flow with a keyboard, a screen reader or large text, and write down what gets in the way.",
    stage: "founding",
    urgency: "most-urgent-now",
    pictogram: "nurse",
    doNow: [
      "Walk one page of this site with only a keyboard and report where focus is lost.",
      "Test a page with a screen reader on fictional screens and describe what was announced.",
      "Check text size, contrast and reduced motion against the written baseline.",
      "Review a plain language explanation for a reader who is new to the idea.",
    ],
    prerequisites: ["Any browser. A screen reader you already use is the most useful tool.", "Lived experience of using assistive technology is valued, and is not required."],
    time: ["About one hour for one page or flow.", "An afternoon for a full pass with a written report."],
    privacyAndConflict: [
      "Test fictional or public screens only. Never record or share your own personal details.",
      "You choose how much of your own situation to share. Nobody asks for a health or disability disclosure.",
    ],
    prohibited: [
      "Testing against real services or real people's accounts.",
      "Posting screenshots that show anyone's personal information.",
    ],
    tasks: { ids: ["07-u09", "06-u08", "12-u05"] },
    review: [COMMON_REVIEW, "A maintainer checks each finding and links the fix to the baseline.", "A barrier that blocks a core step is raised as a bug and fixed before new features."],
    decisions: [COMMON_DECISIONS, "The accessibility baseline is part of the specification. Changing it goes through an open question."],
    links: [
      { label: "Security, accessibility and testing baseline", doc: "docs/spec/16-security-a11y-ops-testing.md" },
      { label: "User experience specification", doc: "docs/spec/17-ux.md" },
      { label: "All one hour tasks", internal: "/contribute/tasks/" },
    ],
  },
  {
    slug: "security-privacy",
    name: "Security and privacy specialists",
    summary: "Look for the ways a boundary could leak or be abused, using made up data only.",
    stage: "founding",
    urgency: "most-urgent-now",
    pictogram: "manager",
    doNow: [
      "Threat-model one boundary: sign in, drafts, email handling or moderation notes.",
      "Write adversarial test cases that try to smuggle in a name, an address or a prompt injection.",
      "Review how a unit handles secrets, logs and error messages.",
      "Report a weakness privately through the route in SECURITY.md.",
    ],
    prerequisites: ["Familiarity with your own field is enough to start.", "Read SECURITY.md before you test anything."],
    time: ["About one hour for one adversarial fixture set.", "A few hours for one boundary review."],
    privacyAndConflict: [
      "Use fictional or synthetic data only. Never real personal data, credentials or someone else's evidence.",
      "Declare any employer or client interest in a tool, vendor or approach you recommend.",
    ],
    prohibited: [
      "Testing any system you do not own or have permission to test.",
      "Publishing a vulnerability before the maintainers have had a chance to respond.",
      "Sending private material to a hosted service that has not been approved.",
    ],
    tasks: { ids: ["07-u01", "07-u04", "11-u04", "11-u05", "11-u06", "14-u12"] },
    review: [COMMON_REVIEW, "Security sensitive changes need a designated reviewer and extra evidence.", "Private reports are acknowledged by a maintainer and handled before any public write up."],
    decisions: [COMMON_DECISIONS, "Your findings shape what is fixed first. They do not give you control over what ships."],
    links: [
      { label: "Private disclosure policy", doc: "SECURITY.md" },
      { label: "Security, accessibility and testing baseline", doc: "docs/spec/16-security-a11y-ops-testing.md" },
      { label: "AI contribution policy", doc: "docs/spec/22-ai-contribution-policy.md" },
      { label: "All one hour tasks", internal: "/contribute/tasks/" },
    ],
  },
  {
    slug: "legal-policy",
    name: "Legal, policy, rights and activism",
    summary: "Help draft the platform rules and policy packs, and review legal source texts, as someone who knows law, rights or public policy.",
    stage: "founding",
    urgency: "needed-now",
    pictogram: "clerk",
    doNow: [
      "Draft or review a platform rule in can_policy, where the community policy packs live. This work is Planned and being built; no pack is in force.",
      "Review a legal source text and its topic index: human rights texts, the EU Charter and a national constitution are being prepared as reference material.",
      "Read an open question about how rules should work, such as who may propose policy, how layers of law conflict, or when old cases are re-examined, and add your evidence.",
      "Test a draft rule against an invented test jurisdiction called Fiktiva City, used so nobody has to rely on a real law.",
      "If you do not use git: the policy repository has a path written for lawyers, activists and policy experts that needs no git.",
    ],
    prerequisites: [
      "Knowledge of law, rights, public administration or policy is the whole requirement. You do not need to code.",
      "A browser is enough to read and comment. Using git is optional.",
    ],
    time: ["About one hour to review one rule or one open question.", "A few hours to review a legal source text article by article."],
    privacyAndConflict: [
      "Work only with public or invented material and open questions. Never bring a real person's case, name or documents.",
      "Say who you work for if an employer, client or campaign could gain from a rule you shape. This is the independence note: nobody's role here is paid by, or answers to, an interest behind a rule.",
    ],
    prohibited: [
      "Giving legal advice to any individual. This role gives none, and the platform is not a legal service.",
      "Presenting your review as an official legal opinion or as the position of any government.",
      "Treating a draft pack as law. A policy pack needs a qualified reviewer before anyone relies on it.",
    ],
    tasks: { areas: ["can-policy"], ids: ["08-u15", "10-u44", "10-u54"] },
    review: [COMMON_REVIEW, "Reviewers with the right background are still being found. Who qualifies is an open question, so your help there counts.", "Ratification of a pack is recorded in the open, with who reviewed and when."],
    decisions: [COMMON_DECISIONS, "Your review improves a draft. It does not make a rule binding, and no role page grants authority over the rules."],
    links: [
      { label: "Community policies repository", doc: "can_policy/" },
      { label: "Contributor guide for policy", doc: "can_policy/CONTRIBUTING.md" },
      { label: "Who reviews legal and policy work", doc: "docs/open-questions/OQ-legal-policy-reviewers.md" },
      { label: "Who may propose policy", doc: "docs/open-questions/OQ-policy-pr-rights.md" },
      { label: "When legal layers conflict", doc: "docs/open-questions/OQ-legal-layer-conflicts.md" },
      { label: "Re-examining past cases", doc: "docs/open-questions/OQ-reresolution-feasibility.md" },
      { label: "Moderation, geography and governance", doc: "docs/spec/06-moderation-geo-governance.md" },
      { label: "All one hour tasks", internal: "/contribute/tasks/" },
    ],
  },
  {
    slug: "translators",
    name: "Translators and localizers",
    summary: "Help prepare plain, accurate wording for other languages, starting with how translation should be done.",
    stage: "founding",
    pictogram: "teacher",
    doNow: [
      "Read the open question on unsupported languages and add which languages matter first and why.",
      "Check a short interface string or a plain language example and say whether the technical meaning survives.",
      "Review the notes on adding a language to this site and point out what a translator would need.",
      "Flag words that do not carry over, such as terms for a stage, a review or a right.",
    ],
    prerequisites: [
      "Fluency in English and one other language, and care about exact meaning.",
      "No coding is needed. The gallery is English only today and built so a second language can be added later.",
    ],
    time: ["About one hour for a short set of strings.", "A few hours for a careful read of one page."],
    privacyAndConflict: [
      "Translate interface strings and made up examples only. Never translate a real person's story or documents.",
      "Do not paste text into an online translation service if it is not public.",
    ],
    prohibited: [
      "Publishing machine translation as final text.",
      "Changing the meaning of a Planned label or of a safety or privacy sentence.",
      "Claiming that a translation is official or legally binding.",
    ],
    tasks: { note: "No bounded translation task is open, because the site has one language for now. Which language comes first is an open question." },
    review: [COMMON_REVIEW, "A second reader of the same language should check technical meaning before text is added."],
    decisions: [COMMON_DECISIONS, "Language order is decided through an open question. Your evidence goes there."],
    links: [
      { label: "Unsupported languages question", doc: "docs/open-questions/OQ-unsupported-language.md" },
      { label: "Cross language reuse question", doc: "docs/open-questions/OQ-cross-language-reuse.md" },
      { label: "Adding a language to this site", doc: "can_gallery/docs/i18n.md" },
      { label: "All one hour tasks", internal: "/contribute/tasks/" },
    ],
  },
  {
    slug: "researchers",
    name: "Researchers",
    summary: "Study how people might use this, using public sources and made up prototypes, with consent and care.",
    stage: "founding",
    pictogram: "student",
    doNow: [
      "Review a flow with a made up scenario and note where a person could be confused.",
      "Gather public sources on how similar civic tools work or fail, and share the links.",
      "Read an open question where evidence is missing and add what the public record shows.",
      "Propose a study plan for later and describe how consent would work.",
    ],
    prerequisites: ["Any research background: design, social science, public health, civic tech or data.", "Read the participation and governance notes first."],
    time: ["About one hour for a source review.", "A few hours for a short written method note."],
    privacyAndConflict: [
      "No recruiting of real affected people yet. The platform is being built and has no real users.",
      "Consent comes first for any future study, and nothing personal is collected here.",
      "Say if you are funded by someone with a stake in the result.",
    ],
    prohibited: [
      "Running a study on real people through this project.",
      "Collecting, scraping or publishing personal data.",
      "Presenting early findings from made up prototypes as results about real communities.",
    ],
    tasks: { note: "No bounded research task is open in the task list right now." },
    review: [COMMON_REVIEW, "A maintainer checks that sources are public and that no real person can be identified."],
    decisions: [COMMON_DECISIONS, "Your evidence can change an open question's default. It does not decide it."],
    links: [
      { label: "Open questions", internal: "/open-questions/" },
      { label: "Participation without money", doc: "docs/spec/20-participation-nonmonetary.md" },
      { label: "Phases and gates", doc: "docs/spec/18-phases-gates.md" },
      { label: "All one hour tasks", internal: "/contribute/tasks/" },
    ],
  },
  {
    slug: "documentation",
    name: "Documentation contributors",
    summary: "Make the project's writing clearer: specification edits, READMEs and plain language rewrites.",
    stage: "founding",
    pictogram: "cook",
    doNow: [
      "Rewrite one confusing paragraph in plain words and propose it as a change.",
      "Fix a README step that fails or is out of date.",
      "Find and report a broken link or a term that is never explained.",
      "Add a short example, labelled as made up, where a page has none.",
    ],
    prerequisites: ["Clear writing and patience. Markdown is the only format used.", "Read the contributor guide to see how a change is proposed."],
    time: ["About one hour for one paragraph or one README step.", "A few hours for a short page."],
    privacyAndConflict: [
      "Use made up examples only, always labelled as fictional examples.",
      "Declare an interest if you write about a product or an organisation you work for.",
    ],
    prohibited: [
      "Changing the meaning of a settled decision while rewording it.",
      "Describing the platform as live, or as an emergency, legal, medical or government service.",
      "Copying text you do not have the right to reuse.",
    ],
    tasks: { note: "No bounded documentation task is open in the task list right now. Good first units may include some." },
    review: [COMMON_REVIEW, "A maintainer checks that meaning is unchanged. Specification edits get a second reviewer."],
    decisions: [COMMON_DECISIONS, "Wording changes never reopen a decision. Disagreements become an open question."],
    links: [
      { label: "How to contribute", doc: "CONTRIBUTING.md" },
      { label: "Good first units", doc: "docs/contributing/good-first-units.md" },
      { label: "The specification index", doc: "docs/spec/00-index.md" },
      { label: "Open source governance", doc: "docs/spec/21-open-source-governance.md" },
      { label: "All one hour tasks", internal: "/contribute/tasks/" },
    ],
  },
];
