// Copies design tokens and compiles open-question headers from ../docs into
// committed files under src/. Outputs are committed so the repo builds standalone.
//   node scripts/sync-content.mjs          write outputs
//   node scripts/sync-content.mjs --check  exit 1 if a write would change a committed file
import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const docs = join(root, "..", "docs");
const check = process.argv.includes("--check");
const tokensSrc = join(docs, "design", "ux", "tokens.json");
const oqDir = join(docs, "open-questions");

if (!existsSync(tokensSrc)) {
  console.log("sync: ../docs not found (standalone checkout), skipping");
  process.exit(0);
}

const cap = (s) => s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());

function tokensCss(t) {
  const block = (theme) => {
    const out = [];
    for (const [k, v] of Object.entries(theme.color)) out.push(`  --can-color-${cap(k)}: ${v.value};`);
    for (const [k, v] of Object.entries(theme.status)) {
      out.push(`  --can-status-${k}-fg: ${v.fg};`, `  --can-status-${k}-bg: ${v.bg};`);
    }
    return out.join("\n");
  };
  const fixed = [];
  for (const [k, v] of Object.entries(t.space)) if (k !== "unit") fixed.push(`  --can-space-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(t.radius)) fixed.push(`  --can-radius-${k}: ${v}px;`);
  fixed.push(
    `  --can-size-min-target: ${t.size.minTarget}px;`,
    `  --can-size-focus-ring: ${t.size.focusRingWidth}px;`,
    `  --can-size-focus-offset: ${t.size.focusRingOffset}px;`,
    `  --can-size-content-max: ${t.size.contentMaxWidth}px;`,
    `  --can-font-sans: ${t.type.family.sans};`,
    `  --can-font-mono: ${t.type.family.mono};`,
    `  --can-motion-fast: ${t.motion.fast}ms;`,
    `  --can-motion-normal: ${t.motion.normal}ms;`,
  );
  return `/* Generated by scripts/sync-content.mjs from docs/design/ux/tokens.json. Do not edit. */
:root {
${block(t.themes.light)}
${fixed.join("\n")}
}

@media (prefers-color-scheme: dark) {
  :root {
${block(t.themes.dark).replace(/^ /gm, "   ")}
  }
}
`;
}

const clean = (s) => s.replace(/\s+/g, " ").replace(/[–—]/g, ", ").trim();
const stripMd = (s) => clean(s.replace(/[*`]/g, "").replace(/\[([^\]]+)\]\([^)]*\)/g, "$1"));

function parseOq(file) {
  const raw = readFileSync(join(oqDir, file), "utf8");
  const id = file.replace(/\.md$/, "");
  let body = raw;
  const meta = {};
  const fm = raw.match(/^---\n([\s\S]*?)\n---\n/);
  if (fm) {
    body = raw.slice(fm[0].length);
    for (const line of fm[1].split("\n")) {
      const m = line.match(/^([\w-]+):\s*(.*)$/);
      if (m) meta[m[1].toLowerCase()] = m[2].replace(/^["']|["']$/g, "");
    }
  }
  const sections = {};
  let title = "";
  let cur = null;
  for (const line of body.split("\n")) {
    const h1 = line.match(/^#\s+(.*)$/);
    const h2 = line.match(/^#{2,3}\s+(.*)$/);
    if (h1 && !title) title = h1[1];
    else if (h2) { cur = h2[1].toLowerCase(); sections[cur] = []; }
    else if (cur) sections[cur].push(line);
    else if (!h1) (sections[""] ??= []).push(line);
  }
  const find = (...keys) => {
    for (const k of Object.keys(sections)) if (keys.some((x) => k.includes(x))) {
      const para = sections[k].join("\n").trim().split(/\n\s*\n/)[0] ?? "";
      return stripMd(para.replace(/^\s*[-*]\s+/gm, ""));
    }
    return "";
  };
  const roles = find("who can help", "roles", "help");
  return {
    id,
    question: stripMd(meta.question || find("question") || title.replace(/^OQ-[\w-]+[:\s-]*/i, "")),
    why: meta.why || find("why it matters", "why"),
    default: meta.default || find("current default", "default"),
    roles: roles ? roles.replace(/\.$/, "").split(/[,;]\s*/).map((r) => r.trim()).filter(Boolean) : [],
    file: `docs/open-questions/${file}`,
  };
}

const oq = existsSync(oqDir)
  ? readdirSync(oqDir).filter((f) => /^OQ-.*\.md$/.test(f)).sort().map(parseOq)
  : [];

const outputs = [
  ["src/content/tokens.json", readFileSync(tokensSrc, "utf8")],
  ["src/app/tokens.css", tokensCss(JSON.parse(readFileSync(tokensSrc, "utf8")))],
  ["src/content/open-questions.json", JSON.stringify(oq, null, 2) + "\n"],
];

let drift = false;
for (const [rel, content] of outputs) {
  const p = join(root, rel);
  const prev = existsSync(p) ? readFileSync(p, "utf8") : null;
  if (prev === content) continue;
  if (check) { console.error(`sync: ${rel} is out of date, run npm run sync:content`); drift = true; }
  else { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, content); console.log(`sync: wrote ${rel}`); }
}
if (drift) process.exit(1);
console.log(check ? "sync: up to date" : `sync: done (${oq.length} open questions)`);
